apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-docs-repo-root
  description: Test Docs Repo, Root Level
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/adrianke77/techdocs-test/blob/master
spec:
  type: documentation
  owner: Grab
  lifecycle: experimental  
